In [4]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']

'''A condição de filtro pode ser omitida, restando somente a expressão. 
Por exemplo, dada uma lista de strings, poderíamos filtrar, 
eliminando aquelas de tamanho 2 ou menores, e também converter as strings para letras maiúsculas'''

'A condição de filtro pode ser omitida, restando somente a expressão. \nPor exemplo, dada uma lista de strings, poderíamos filtrar, \neliminando aquelas de tamanho 2 ou menores, e também converter as strings para letras maiúsculas'

In [3]:
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [ ]:
# dict_comp = {expr-chave:expr-valor for value in collection if condition}

# set_comp = {expr for value in collection if condition}

In [5]:
{len(x) for x in strings}

{1, 2, 3, 4, 6}

In [7]:
set(map(len,strings))

{1, 2, 3, 4, 6}

In [8]:
{val : index for index, val in enumerate(strings)}

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [12]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'], ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

In [15]:
[names_of_interests for name in all_data if name.count('e') >=2 ]
[name for bla in all_data for name in bla if name.count('e') >=2]

['Steven']

In [23]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [29]:
lista = [x for tupla in some_tuples for x in tupla]

In [30]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
[[x for x in tupla] for tupla in some_tuples]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']

In [3]:
strings.sort(key=lambda x: len(set(list(x))))

In [4]:
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

# NumPy

In [1]:
import numpy as np

In [3]:
data = np.random.randn(2,3)
data

array([[-0.28051428, -1.68213306, -0.29715662],
       [-0.77913394,  0.41948176, -1.32553708]])

In [4]:
data * 10

array([[ -2.80514282, -16.82133064,  -2.97156617],
       [ -7.79133938,   4.19481757, -13.25537085]])

In [5]:
data + data

array([[-0.56102856, -3.36426613, -0.59431323],
       [-1.55826788,  0.83896351, -2.65107417]])

In [7]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0 ,1]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2.shape

(2, 4)

In [18]:
arr2.ndim

2

In [23]:
np.ones((4, 6, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [27]:
np.arange(9).dtype

dtype('int64')

In [29]:
np.empty((2, 3))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [30]:
np.empty((2, 3))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [35]:
arr1 = np.array([1 ,2, 3])

In [36]:
arr1.dtype

dtype('int64')

In [55]:
arr2 = np.array([1, 2, 3], dtype=np.int64)

In [34]:
arr2.dtype

dtype('int64')

In [37]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
arr.dtype

dtype('int64')

In [40]:
float_arr = arr.astype(np.float64)

In [41]:
float_arr.dtype

dtype('float64')

In [43]:
from random import randint


In [45]:
arr = np.arange(10)

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr[5:8] = 12

In [57]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [58]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2[1, :2]

array([4, 5])

In [64]:
arr2[:2, 2]

array([3, 6])

In [65]:
arr2[:, :1]

array([[1],
       [4],
       [7]])

In [66]:
arr2[:2,1:] = 0

In [67]:
arr2

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])